name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Trigger Render deployment via API
      - name: Trigger deployment on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "🚀 Triggering deployment on Render..."
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d '' \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"

      # 3️⃣ Confirm success
      - name: Confirm
        run: echo "✅ Deployment triggered successfully on Render"
