name: Deploy to Render

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Render CLI correctly
      - name: Install Render CLI
        run: |
          curl -fsSL https://render.com/install.sh -o install.sh
          bash install.sh
          echo "/root/.render/bin" >> $GITHUB_PATH

      # 3️⃣ Verify the CLI is installed
      - name: Verify Render CLI
        run: |
          which render
          render --version

      # 4️⃣ Trigger deployment on Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deployment for service: $RENDER_SERVICE_ID"
          render deploy \
            --api-key "$RENDER_API_KEY" \
            --service-id "$RENDER_SERVICE_ID"
